name: GitHub Release

on:

  pull_request:

  push:
    tags: '*'

  schedule:
    - cron: 0 0 * * 0

jobs:

  build:

    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@v1
        with:
          fetch-depth: 1

      - name: Prepare Environment
        run: docker system prune --all --force --volumes
      - name: Happy Eyeballs
        run: wget -qO- 'https://github.com/tianon/pgp-happy-eyeballs/raw/master/hack-my-builds.sh' | bash

      - name: Check Kernel Config
        run: |
          kernDups="$(files/kernel-config.d/.check-dups.sh)"
          if [ -n "$kernDups" ]; then
            echo >&2 "KERNEL CONFIG DUPLICATES!"
            echo >&2 "$kernDups"
            exit 1
          fi

      - name: Build ISO
        run: |
          set -Eeuo pipefail -x
          docker build -t boot2docker/boot2docker .
          docker run --rm boot2docker/boot2docker > boot2docker.iso

      - name: '"ls"'
        run: ls -lh boot2docker.iso

      - name: '"pwd" and echo GH workspace'
        run: pwd; echo ${{ GITHUB_WORKSPACE }}

      - name: '"docker images"'
        run: docker images

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: boot2docker
          path: boot2docker.iso

      - name: Publish Release
        uses: ncipollo/release-action@v1
        with:
          artifacts: ${{ GITHUB_WORKSPACE }}/boot2docker.iso
          token: ${{ secrets.GITHUB_TOKEN }}
          allowUpdates: true
